"use strict";

const { GuardCapability, SinkKind, SourceKind } = require("../security/semantics");

const EXTERNAL_SOURCES = Object.freeze([
  SourceKind.HTTP_INPUT,
  SourceKind.PROCESS_INPUT,
  SourceKind.FILE_UPLOAD,
  SourceKind.EXTERNAL_INPUT,
]);

const STANDARD_PROPAGATORS = Object.freeze([
  "assignment", "argument", "return", "property", "template", "concatenation", "collection", "alias",
]);

const RULES = Object.freeze([
  {
    id: "potential-ssrf",
    title: "Potential server-side request forgery",
    sourceKinds: EXTERNAL_SOURCES,
    propagators: STANDARD_PROPAGATORS,
    sinkKinds: [SinkKind.HTTP_REQUEST],
    recommendedGuards: [GuardCapability.VALIDATE_SCHEME, GuardCapability.BLOCK_PRIVATE_IP, GuardCapability.URL_POLICY],
    severity: "high",
    impact: "Server-side network access",
    cwe: "CWE-918",
    core: true,
  },
  {
    id: "potential-command-injection",
    title: "Potential command injection",
    sourceKinds: EXTERNAL_SOURCES,
    propagators: STANDARD_PROPAGATORS,
    sinkKinds: [SinkKind.COMMAND_EXEC],
    recommendedGuards: [GuardCapability.SHELL_ESCAPE],
    sanitizerCapabilities: [GuardCapability.SHELL_ESCAPE],
    severity: "critical",
    impact: "Operating-system command execution",
    cwe: "CWE-78",
    core: true,
  },
  {
    id: "potential-sql-injection",
    title: "Potential SQL injection",
    sourceKinds: EXTERNAL_SOURCES,
    propagators: STANDARD_PROPAGATORS,
    sinkKinds: [SinkKind.SQL_QUERY],
    recommendedGuards: [GuardCapability.SQL_PARAMETERIZATION],
    sanitizerCapabilities: [GuardCapability.SQL_PARAMETERIZATION],
    severity: "high",
    impact: "Database query execution",
    cwe: "CWE-89",
    core: true,
  },
  {
    id: "potential-path-traversal",
    title: "Potential path traversal",
    sourceKinds: EXTERNAL_SOURCES,
    propagators: STANDARD_PROPAGATORS,
    sinkKinds: [SinkKind.FILE_ACCESS],
    recommendedGuards: [GuardCapability.PATH_CONFINEMENT],
    severity: "high",
    impact: "Filesystem access",
    cwe: "CWE-22",
    sanitizerCapabilities: [GuardCapability.PATH_CONFINEMENT],
    core: true,
  },
  {
    id: "potential-open-redirect",
    title: "Potential untrusted redirect",
    sourceKinds: EXTERNAL_SOURCES,
    sinkKinds: [SinkKind.REDIRECT],
    recommendedGuards: [GuardCapability.URL_POLICY],
    severity: "medium",
    impact: "Browser navigation",
    cwe: "CWE-601",
    core: false,
  },
  {
    id: "potential-unsafe-output",
    title: "Potential unsafe response output",
    sourceKinds: EXTERNAL_SOURCES,
    sinkKinds: [SinkKind.RESPONSE_OUTPUT],
    recommendedGuards: [GuardCapability.OUTPUT_ENCODING],
    severity: "medium",
    impact: "Untrusted response content",
    cwe: "CWE-79",
    core: false,
  },
  {
    id: "potential-unsafe-deserialization",
    title: "Potential unsafe deserialization",
    sourceKinds: EXTERNAL_SOURCES,
    sinkKinds: [SinkKind.DESERIALIZATION],
    recommendedGuards: [GuardCapability.DESERIALIZATION_ALLOWLIST],
    sanitizerCapabilities: [GuardCapability.DESERIALIZATION_ALLOWLIST],
    severity: "critical",
    impact: "Object construction from untrusted data",
    cwe: "CWE-502",
    propagators: STANDARD_PROPAGATORS,
    core: true,
  },
  {
    id: "potential-dynamic-execution",
    title: "Potential dynamic code execution",
    sourceKinds: EXTERNAL_SOURCES,
    sinkKinds: [SinkKind.DYNAMIC_EXEC],
    recommendedGuards: [GuardCapability.INPUT_VALIDATION],
    severity: "critical",
    impact: "Dynamic expression or code execution",
    cwe: "CWE-95",
    core: false,
  },
]);

module.exports = { EXTERNAL_SOURCES, RULES, STANDARD_PROPAGATORS };
