"use strict";

const { GuardCapability, SinkKind } = require("./semantics");

function sink(input) {
  return Object.freeze({
    role: "sink",
    returnsTaint: false,
    receiverTypes: [],
    taintReceiver: false,
    taintArguments: [],
    qualifiedNames: [],
    moduleNames: [],
    callNames: [],
    callForms: [],
    ...input,
  });
}

function guard(input) {
  return Object.freeze({
    role: "guard",
    returnsTaint: false,
    receiverTypes: [],
    taintReceiver: false,
    taintArguments: [],
    qualifiedNames: [],
    moduleNames: [],
    callNames: [],
    callForms: [],
    ...input,
  });
}

const SUPPLEMENTAL_SEMANTIC_MODELS = Object.freeze([
  sink({
    id: "javascript.database.dynamic-query",
    languages: ["javascript", "typescript"],
    moduleNames: ["mysql", "mysql2", "pg", "sqlite3", "sequelize", "typeorm", "knex", "@prisma/client"],
    qualifiedNames: ["Database.query", "Database.execute", "Sequelize.query", "EntityManager.query"],
    receiverTypes: ["Database", "Connection", "Pool", "Client", "EntityManager", "Sequelize"],
    callNames: ["query", "execute", "raw", "$queryRaw", "$executeRaw"],
    taintArguments: [0],
    sinkKind: SinkKind.SQL_QUERY,
    category: "database",
    callForms: ["instance-method"],
    requiresModuleIdentity: true,
    patternReceiverAgnostic: true,
    syntaxReceiverNames: ["sequelize"],
    verifiedSyntaxReceiverNames: ["models.sequelize"],
  }),
  sink({
    id: "javascript.dynamic-code",
    languages: ["javascript", "typescript"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["eval", "Function"],
    callNames: ["eval", "Function"],
    taintArguments: [0],
    sinkKind: SinkKind.DYNAMIC_EXEC,
    category: "expression",
    callForms: ["global", "constructor"],
  }),
  sink({
    id: "javascript.string-timer",
    languages: ["javascript", "typescript"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["setTimeout", "setInterval"],
    callNames: ["setTimeout", "setInterval"],
    taintArguments: [0],
    sinkKind: SinkKind.DYNAMIC_EXEC,
    category: "expression",
    callForms: ["global"],
  }),
  sink({
    id: "javascript.axios.request",
    languages: ["javascript", "typescript"],
    moduleNames: ["axios"],
    qualifiedNames: ["axios.get", "axios.post", "axios.put", "axios.patch", "axios.delete"],
    receiverTypes: ["Axios", "AxiosInstance"],
    callNames: ["get", "post", "put", "patch", "delete"],
    taintArguments: [0],
    sinkKind: SinkKind.HTTP_REQUEST,
    category: "network",
    callForms: ["namespace-import", "default-import-member", "instance-method"],
  }),
  sink({
    id: "javascript.http-redirect",
    languages: ["javascript", "typescript"],
    qualifiedNames: ["Response.redirect"],
    receiverTypes: ["Response", "express.Response"],
    callNames: ["redirect"],
    taintArguments: [0],
    sinkKind: SinkKind.REDIRECT,
    category: "redirect",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
    syntaxReceiverNames: ["res", "response"],
    verifiedSyntaxReceiverNames: ["res", "response"],
  }),
  sink({
    id: "javascript.response-output",
    languages: ["javascript", "typescript"],
    qualifiedNames: ["Response.send", "Response.write", "Response.end"],
    receiverTypes: ["Response", "express.Response", "http.ServerResponse"],
    callNames: ["send", "write", "end"],
    taintArguments: [0],
    sinkKind: SinkKind.RESPONSE_OUTPUT,
    category: "output",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
    syntaxReceiverNames: ["res", "response"],
    verifiedSyntaxReceiverNames: ["res", "response"],
    rejectWhen: [{
      when: { argument: { index: 0, pattern: "^\\s*\\{" } },
      reason: "Express serializes an object-literal response as structured data rather than executable markup.",
    }],
    syntaxForms: [{ form: "member-assignment", members: ["innerHTML", "outerHTML"] }],
  }),
  guard({
    id: "javascript.html-output-encoding",
    languages: ["javascript", "typescript"],
    moduleNames: ["dompurify", "sanitize-html", "escape-html", "html-escaper"],
    qualifiedNames: ["DOMPurify.sanitize", "sanitizeHtml", "escapeHtml"],
    receiverTypes: ["DOMPurify"],
    callNames: ["sanitize", "sanitizeHtml", "escapeHtml"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.OUTPUT_ENCODING],
    applicableSinkKinds: [SinkKind.RESPONSE_OUTPUT],
    callForms: ["static-method", "function", "default-import", "named-import"],
    fallbackByCallName: true,
  }),
  guard({
    id: "javascript.path-confinement-check",
    languages: ["javascript", "typescript"],
    qualifiedNames: ["String.startsWith"],
    receiverTypes: ["String", "string"],
    callNames: ["startsWith"],
    taintArguments: [0],
    taintReceiver: true,
    guardCapabilities: [GuardCapability.PATH_CONFINEMENT],
    applicableSinkKinds: [SinkKind.FILE_ACCESS],
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
    syntaxForms: [{ form: "method-call", members: ["startsWith"] }],
  }),
  guard({
    id: "javascript.input-validation",
    languages: ["javascript", "typescript"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["validate", "sanitize", "parse", "safeParse"],
    callNames: ["validate", "sanitize", "parse", "safeParse"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.INPUT_VALIDATION],
    applicableSinkKinds: Object.values(SinkKind),
    callForms: ["function"],
  }),
  guard({
    id: "javascript.path-canonicalization",
    languages: ["javascript", "typescript"],
    moduleNames: ["path", "node:path"],
    qualifiedNames: ["path.normalize", "path.resolve", "path.basename"],
    receiverTypes: ["path"],
    callNames: ["normalize", "resolve", "basename"],
    taintArguments: [0],
    taintRestFrom: 0,
    guardCapabilities: [GuardCapability.PATH_CANONICALIZATION],
    applicableSinkKinds: [SinkKind.FILE_ACCESS],
    callForms: ["namespace-import", "default-import-member", "require-member"],
  }),
  sink({
    id: "php.dynamic-code",
    languages: ["php"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["eval", "assert"],
    callNames: ["eval", "assert"],
    taintArguments: [0],
    sinkKind: SinkKind.DYNAMIC_EXEC,
    category: "expression",
    callForms: ["function"],
  }),
  sink({
    id: "php.curl-option-url",
    languages: ["php"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["curl_setopt"],
    callNames: ["curl_setopt"],
    taintArguments: [2],
    sinkKind: SinkKind.HTTP_REQUEST,
    category: "network",
    callForms: ["function"],
    argumentExpectedValues: [{
      index: 1,
      values: ["CURLOPT_URL"],
      matchMode: "identifier",
      reason: "curl_setopt is an HTTP URL sink only when CURLOPT_URL is selected.",
    }],
  }),
  sink({
    id: "php.response-output",
    languages: ["php"],
    sinkKind: SinkKind.RESPONSE_OUTPUT,
    category: "output",
    syntaxForms: [{ form: "keyword", values: ["echo", "print"] }],
    staticOperandSafe: true,
  }),
  sink({
    id: "php.response-header",
    languages: ["php"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["header"],
    callNames: ["header"],
    taintArguments: [0],
    sinkKind: SinkKind.REDIRECT,
    category: "redirect",
    callForms: ["function"],
    staticOperandSafe: true,
  }),
  sink({
    id: "php.dynamic-include",
    languages: ["php"],
    sinkKind: SinkKind.FILE_ACCESS,
    category: "file",
    syntaxForms: [{ form: "keyword", values: ["include", "include_once", "require", "require_once"] }],
    staticOperandSafe: true,
  }),
  guard({
    id: "php.html-output-encoding",
    languages: ["php"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["htmlspecialchars", "htmlentities", "esc_html", "e"],
    callNames: ["htmlspecialchars", "htmlentities", "esc_html", "e"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.OUTPUT_ENCODING],
    applicableSinkKinds: [SinkKind.RESPONSE_OUTPUT],
    callForms: ["function"],
  }),
  guard({
    id: "php.shell-argument-escape",
    languages: ["php"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["escapeshellarg", "escapeshellcmd"],
    callNames: ["escapeshellarg", "escapeshellcmd"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.SHELL_ESCAPE],
    applicableSinkKinds: [SinkKind.COMMAND_EXEC],
    callForms: ["function"],
  }),
  sink({
    id: "python.dynamic-code",
    languages: ["python"],
    global: true,
    fallbackByCallName: true,
    qualifiedNames: ["eval", "exec", "compile"],
    callNames: ["eval", "exec", "compile"],
    taintArguments: [0],
    sinkKind: SinkKind.DYNAMIC_EXEC,
    category: "expression",
    callForms: ["function"],
  }),
  sink({
    id: "python.http-redirect",
    languages: ["python"],
    global: true,
    fallbackByCallName: true,
    moduleNames: ["django.shortcuts", "flask"],
    qualifiedNames: ["django.shortcuts.redirect", "flask.redirect", "redirect"],
    callNames: ["redirect"],
    taintArguments: [0],
    sinkKind: SinkKind.REDIRECT,
    category: "redirect",
    callForms: ["function", "named-import"],
  }),
  guard({
    id: "python.html-output-encoding",
    languages: ["python"],
    moduleNames: ["bleach", "html", "markupsafe"],
    qualifiedNames: ["bleach.clean", "html.escape", "markupsafe.escape"],
    callNames: ["clean", "escape"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.OUTPUT_ENCODING],
    applicableSinkKinds: [SinkKind.RESPONSE_OUTPUT],
    callForms: ["module-function", "named-import"],
  }),
  sink({
    id: "python.browser-navigation",
    languages: ["python"],
    moduleNames: ["selenium", "playwright"],
    qualifiedNames: ["WebDriver.get", "Page.goto", "Page.navigate"],
    receiverTypes: ["WebDriver", "Page", "Browser"],
    callNames: ["get", "goto", "navigate"],
    taintArguments: [0],
    sinkKind: SinkKind.HTTP_REQUEST,
    category: "network",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
    patternCallNames: ["goto", "navigate"],
    syntaxForms: [{ form: "member-call", receivers: ["driver", "browser", "page"], members: ["get", "goto", "navigate"] }],
  }),
  sink({
    id: "java.spring.expression",
    languages: ["java"],
    moduleNames: ["org.springframework.expression"],
    qualifiedNames: ["ExpressionParser.parseExpression"],
    receiverTypes: ["ExpressionParser", "SpelExpressionParser"],
    callNames: ["parseExpression"],
    taintArguments: [0],
    sinkKind: SinkKind.DYNAMIC_EXEC,
    category: "expression",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
  }),
  sink({
    id: "java.servlet.redirect",
    languages: ["java"],
    moduleNames: ["jakarta.servlet.http", "javax.servlet.http"],
    qualifiedNames: ["HttpServletResponse.sendRedirect"],
    receiverTypes: ["HttpServletResponse"],
    callNames: ["sendRedirect"],
    taintArguments: [0],
    sinkKind: SinkKind.REDIRECT,
    category: "redirect",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
  }),
  sink({
    id: "java.directory-lookup",
    languages: ["java"],
    moduleNames: ["javax.naming", "jakarta.naming", "javax.naming.directory"],
    qualifiedNames: ["Context.lookup", "DirContext.search"],
    receiverTypes: ["Context", "InitialContext", "DirContext"],
    callNames: ["lookup", "search"],
    taintArguments: [0],
    sinkKind: SinkKind.DIRECTORY_LOOKUP,
    category: "directory",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
  }),
  guard({
    id: "java.path-canonicalization",
    languages: ["java"],
    qualifiedNames: ["Path.normalize", "Path.toRealPath", "File.getCanonicalPath"],
    receiverTypes: ["Path", "File"],
    callNames: ["normalize", "toRealPath", "getCanonicalPath"],
    taintReceiver: true,
    guardCapabilities: [GuardCapability.PATH_CANONICALIZATION],
    applicableSinkKinds: [SinkKind.FILE_ACCESS],
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
  }),
  guard({
    id: "java.html-output-encoding",
    languages: ["java"],
    qualifiedNames: ["Encode.forHtml", "HtmlUtils.htmlEscape", "StringEscapeUtils.escapeHtml"],
    receiverTypes: ["Encode", "HtmlUtils", "StringEscapeUtils"],
    callNames: ["forHtml", "htmlEscape", "escapeHtml"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.OUTPUT_ENCODING],
    applicableSinkKinds: [SinkKind.RESPONSE_OUTPUT],
    callForms: ["static-method"],
  }),
  sink({
    id: "dotnet.database.dynamic-query",
    languages: ["csharp"],
    moduleNames: ["System.Data.SqlClient", "Microsoft.Data.SqlClient", "Microsoft.EntityFrameworkCore"],
    qualifiedNames: ["SqlCommand", "DatabaseFacade.ExecuteSqlRaw", "RelationalQueryableExtensions.FromSqlRaw"],
    receiverTypes: ["SqlCommand", "DatabaseFacade", "DbSet"],
    callNames: ["SqlCommand", "FromSqlRaw", "ExecuteSqlRaw", "ExecuteReader", "ExecuteScalar", "ExecuteNonQuery"],
    taintArguments: [0],
    sinkKind: SinkKind.SQL_QUERY,
    category: "database",
    callForms: ["constructor", "instance-method", "static-method"],
    patternReceiverAgnostic: true,
  }),
  sink({
    id: "dotnet.filesystem-access",
    languages: ["csharp"],
    moduleNames: ["System.IO"],
    qualifiedNames: ["File.ReadAllText", "File.WriteAllText", "File.Delete", "File.Move", "File.Copy", "Directory.Delete", "Path.Combine"],
    receiverTypes: ["File", "Directory", "Path"],
    callNames: ["ReadAllText", "WriteAllText", "Delete", "Move", "Copy", "Open", "Create", "Combine"],
    taintArguments: [0],
    sinkKind: SinkKind.FILE_ACCESS,
    category: "file",
    callForms: ["static-method"],
  }),
  sink({
    id: "dotnet.http-request",
    languages: ["csharp"],
    moduleNames: ["System.Net.Http"],
    qualifiedNames: ["HttpClient.GetAsync", "HttpClient.PostAsync", "HttpClient.SendAsync"],
    receiverTypes: ["HttpClient"],
    callNames: ["GetAsync", "PostAsync", "SendAsync"],
    taintArguments: [0],
    sinkKind: SinkKind.HTTP_REQUEST,
    category: "network",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
  }),
  sink({
    id: "dotnet.redirect",
    languages: ["csharp"],
    qualifiedNames: ["Controller.Redirect", "HttpResponse.Redirect"],
    receiverTypes: ["Controller", "HttpResponse"],
    callNames: ["Redirect", "RedirectToAction"],
    taintArguments: [0],
    sinkKind: SinkKind.REDIRECT,
    category: "redirect",
    callForms: ["instance-method", "function"],
    patternReceiverAgnostic: true,
  }),
  sink({
    id: "dotnet.native-deserialization",
    languages: ["csharp"],
    moduleNames: ["System.Runtime.Serialization", "System.Web.UI"],
    qualifiedNames: ["BinaryFormatter.Deserialize", "LosFormatter.Deserialize", "NetDataContractSerializer.Deserialize"],
    receiverTypes: ["BinaryFormatter", "LosFormatter", "NetDataContractSerializer"],
    callNames: ["Deserialize"],
    taintArguments: [0],
    sinkKind: SinkKind.DESERIALIZATION,
    category: "deserialization",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
  }),
  guard({
    id: "dotnet.html-output-encoding",
    languages: ["csharp"],
    moduleNames: ["System.Text.Encodings.Web", "System.Net", "System.Web"],
    qualifiedNames: ["HtmlEncoder.Encode", "WebUtility.HtmlEncode", "HttpUtility.HtmlEncode"],
    receiverTypes: ["HtmlEncoder", "WebUtility", "HttpUtility"],
    callNames: ["Encode", "HtmlEncode"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.OUTPUT_ENCODING],
    applicableSinkKinds: [SinkKind.RESPONSE_OUTPUT],
    callForms: ["static-method", "instance-method"],
  }),
  sink({
    id: "go.database.dynamic-query",
    languages: ["go"],
    moduleNames: ["database/sql"],
    qualifiedNames: ["sql.DB.Query", "sql.DB.QueryRow", "sql.DB.Exec", "sql.DB.Prepare"],
    receiverTypes: ["sql.DB", "sql.Tx"],
    callNames: ["Query", "QueryRow", "Exec", "Prepare", "QueryContext", "QueryRowContext", "ExecContext", "PrepareContext"],
    taintArguments: [0],
    sinkKind: SinkKind.SQL_QUERY,
    category: "database",
    callForms: ["instance-method"],
    patternReceiverAgnostic: true,
  }),
  sink({
    id: "go.filesystem-access",
    languages: ["go"],
    moduleNames: ["os"],
    qualifiedNames: ["os.Open", "os.OpenFile", "os.ReadFile", "os.WriteFile", "os.Remove", "os.Rename", "os.Create"],
    callNames: ["Open", "OpenFile", "ReadFile", "WriteFile", "Remove", "Rename", "Create"],
    taintArguments: [0],
    sinkKind: SinkKind.FILE_ACCESS,
    category: "file",
    callForms: ["module-function"],
  }),
  sink({
    id: "go.http-request",
    languages: ["go"],
    moduleNames: ["net/http"],
    qualifiedNames: ["http.Get", "http.Post", "http.NewRequest", "http.Client.Do"],
    receiverTypes: ["http.Client"],
    callNames: ["Get", "Post", "NewRequest", "Do"],
    taintArguments: [0],
    sinkKind: SinkKind.HTTP_REQUEST,
    category: "network",
    callForms: ["module-function", "instance-method"],
    patternReceiverAgnostic: true,
    patternCallNames: ["Do"],
  }),
  sink({
    id: "go.template-trust-bypass",
    languages: ["go"],
    moduleNames: ["html/template"],
    qualifiedNames: ["template.HTML", "template.JS", "template.URL"],
    callNames: ["HTML", "JS", "URL"],
    taintArguments: [0],
    sinkKind: SinkKind.RESPONSE_OUTPUT,
    category: "output",
    callForms: ["module-function"],
  }),
  sink({
    id: "go.native-deserialization",
    languages: ["go"],
    moduleNames: ["encoding/gob", "encoding/xml"],
    qualifiedNames: ["gob.Decoder.Decode", "xml.Decoder.Decode"],
    receiverTypes: ["gob.Decoder", "xml.Decoder"],
    callNames: ["Decode"],
    taintArguments: [0],
    sinkKind: SinkKind.DESERIALIZATION,
    category: "deserialization",
    callForms: ["instance-method"],
    requiresModuleIdentity: true,
    patternReceiverAgnostic: true,
  }),
  guard({
    id: "go.numeric-conversion",
    languages: ["go"],
    moduleNames: ["strconv"],
    qualifiedNames: ["strconv.Atoi", "strconv.ParseInt", "strconv.ParseUint", "strconv.ParseBool"],
    callNames: ["Atoi", "ParseInt", "ParseUint", "ParseBool"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.NUMERIC_ONLY],
    applicableSinkKinds: [SinkKind.COMMAND_EXEC, SinkKind.SQL_QUERY],
    callForms: ["module-function"],
  }),
  guard({
    id: "go.html-output-encoding",
    languages: ["go"],
    moduleNames: ["html"],
    qualifiedNames: ["html.EscapeString"],
    callNames: ["EscapeString"],
    taintArguments: [0],
    guardCapabilities: [GuardCapability.OUTPUT_ENCODING],
    applicableSinkKinds: [SinkKind.RESPONSE_OUTPUT],
    callForms: ["module-function"],
  }),
]);

module.exports = { SUPPLEMENTAL_SEMANTIC_MODELS };
